<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Location::insert([
            ['name'=>'Dhaka'],
            ['name'=>'Narsingdi'],
            ['name'=>'Brahmanbaria'],
            ['name'=>'Gazipur'],
            ['name'=>'Tangail'],
            ['name'=>'Sylhet'],
            ['name'=>'Moulvibazar'],
            ['name'=>'Habiganj'],
            ['name'=>'Sunamganj'],
            ['name'=>'Comilla'],
            ['name'=>'Chittagong'],
            ['name'=>'Coxs Bazar'],
            ['name'=>'Feni'],
            ['name'=>'Noakhali'],
            ['name'=>'Rangamati'],
            ['name'=>'Khulna'],
            ['name'=>'Jessore'],
            ['name'=>'Satkhira'],
            ['name'=>'Bagerhat'],
            ['name'=>'Jhenaidah'],
            ['name'=>'Barisal'],
            ['name'=>'Patuakhali'],
            ['name'=>'Bhola'],
            ['name'=>'Jhalokathi'],
            ['name'=>'Pirojpur'],
            ['name'=>'Rangpur'],
            ['name'=>'Dinajpur'],
            ['name'=>'Thakurgaon'],
            ['name'=>'Lalmonirhat'],
            ['name'=>'Kurigram'],
            ['name'=>'Rajshahi'],
            ['name'=>'Natore'],
            ['name'=>'Bogra'],
            ['name'=>'Pabna'],
            ['name'=>'Naogaon'],
            ['name'=>'Mymensingh'],
            ['name'=>'Jamalpur'],
            ['name'=>'Netrokona'],
            ['name'=>'Sherpur'],
            ['name'=>'Chittagong Hill Tracts'],
            ['name'=>'Bandarban'],
            ['name'=>'Khagrachhari'],
            ['name'=>'Narail'],
            ['name'=>'Sirajganj'],
            ['name'=>'Joypurhat'],
            ['name'=>'Munshiganj'],
            ['name'=>'Narayanganj'],
            ['name'=>'Maulvi Bazar'],
            ['name'=>'Chandpur'],
            ['name'=>'Nilphamari'],
            ['name'=>'Panchagarh'],
            ['name'=>'Bhola Hill'],
            ['name'=>'Fenchuganj'],
            ['name'=>'Gopalganj'],
            ['name'=>'Kishoreganj'],
            ['name'=>'Shariatpur'],
            ['name'=>'Lakshmipur'],
            ['name'=>'Brahmanbaria North'],
            ['name'=>'Brahmanbaria South'],
            ['name'=>'Coxs Bazar North'],
            ['name'=>'Coxs Bazar South'],
            ['name'=>'Satkhira North'],
            ['name'=>'Satkhira South'],
            ['name'=>'Jessore North'],
            ['name'=>'Jessore South'],
            ['name'=>'Khulna North'],
            ['name'=>'Khulna South'],
            ['name'=>'Rangamati East'],
            ['name'=>'Rangamati West'],
            ['name'=>'Bandarban East'],
            ['name'=>'Bandarban West'],
            ['name'=>'Pirojpur North'],
            ['name'=>'Pirojpur South'],
            ['name'=>'Patuakhali North'],
            ['name'=>'Patuakhali South'],
            ['name'=>'Barisal North'],
            ['name'=>'Barisal South'],
            ['name'=>'Dinajpur North'],
            ['name'=>'Dinajpur South'],
            ['name'=>'Thakurgaon North'],
            ['name'=>'Thakurgaon South'],
            ['name'=>'Lalmonirhat North'],
            ['name'=>'Lalmonirhat South'],
            ['name'=>'Kurigram North'],
            ['name'=>'Kurigram South'],
            ['name'=>'Naogaon North'],
            ['name'=>'Naogaon South'],
            ['name'=>'Bogra North'],
            ['name'=>'Bogra South'],
            ['name'=>'Mymensingh North'],
            ['name'=>'Mymensingh South'],
            ['name'=>'Dhaka North'],
            ['name'=>'Dhaka South'],
            ['name'=>'Gazipur North'],
            ['name'=>'Gazipur South'],
            ['name'=>'Narsingdi North'],
            ['name'=>'Narsingdi South'],
            ['name'=>'Munshiganj North'],
            ['name'=>'Munshiganj South'],
            ['name'=>'Narayanganj North'],
            ['name'=>'Narayanganj South'],
            ['name'=>'Sylhet North'],
            ['name'=>'Sylhet South'],
            ['name'=>'Moulvibazar North'],
            ['name'=>'Moulvibazar South'],
            ['name'=>'Habiganj North'],
            ['name'=>'Habiganj South'],
            ['name'=>'Sunamganj North'],
            ['name'=>'Sunamganj South'],
            ['name'=>'Comilla North'],
            ['name'=>'Comilla South'],
            ['name'=>'Chittagong North'],
            ['name'=>'Chittagong South'],
            ['name'=>'Feni North'],
            ['name'=>'Feni South'],
            ['name'=>'Noakhali North'],
            ['name'=>'Noakhali South'],
            ['name'=>'Khagrachhari East'],
            ['name'=>'Khagrachhari West'],
            ['name'=>'Chandpur North'],
            ['name'=>'Chandpur South'],
            ['name'=>'Gopalganj North'],
            ['name'=>'Gopalganj South'],
            ['name'=>'Shariatpur North'],
            ['name'=>'Shariatpur South'],
            ['name'=>'Lakshmipur North'],
            ['name'=>'Lakshmipur South'],
            ['name'=>'Kishoreganj North'],
            ['name'=>'Kishoreganj South'],
            ['name'=>'Fenchuganj North'],
            ['name'=>'Fenchuganj South']

        ]);
    }
}
